name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Syntax-Fehler in der .bashrc reparieren
            sed -i "s/alias dc='docker-compose'#/alias dc='docker-compose' #/g" ~/.bashrc
            
            # 2. Projekt-Ordner sicherstellen und klonen, falls er nicht existiert
            mkdir -p /opt/stacks
            if [ ! -d "/opt/stacks/hizbulazam-main/.git" ]; then
              cd /opt/stacks
              git clone https://github.com/fecbatino/hizbulazam.git hizbulazam-main
            fi
            
            # 3. App aktualisieren und bauen
            cd /opt/stacks/hizbulazam-main
            git pull origin main
            npm install
            npm run build
